@startuml Cat::action()

participant "利用者" as Client
entity Cat
entity CatAI as AI
entity CatActionRepository as ActionRepository
entity Bonding
entity CatAction as Action
entity Emotion
entity ActionExecutor
entity Position
entity ActionSelector as Selector


Client -> Cat: action(action_context)
activate Cat
Cat -> AI: action(action_context)
activate AI
AI -> Action: action(action_context)
activate Action
alt not CurrentAction.IsInprogress()
    Action -> Selector: select(emotion)
    activate Selector
    Selector --> Action: action_executer = new ConcreteActionExecutor()
    deactivate Selector
    Action -> Action: set new CurrentAction(action_executer)
end alt
Action --> CurrentAction: action(context)
activate CurrentAction
CurrentAction --> ActionExecutor: execute(action_context)
activate ActionExecutor
ActionExecutor --> CurrentAction: new ActionResult(xxx)
deactivate ActionExecutor
CurrentAction -> GameTimeManager: getCurrentTime()
activate GameTimeManager
GameTimeManager --> CurrentAction: game_time
deactivate GameTimeManager 
CurrentAction -> CurrentAction: update_status()
CurrentAction --> Action: action_result
deactivate CurrentAction
Action --> AI: action_result
deactivate Action
AI -> Bonding: update(action_result.bonding_change)
activate Bonding
Bonding -> BondingFactory: create(bonding_level, bonding_gauge)
activate BondingFactory
BondingFactory --> Bonding: new ConcreteBonding()
deactivate BondingFactory
Bonding --> AI: new Bonding()
deactivate Bonding
AI -> Bonding: updateByTime()
activate Bonding
Bonding -> GameTimeManager: getGameTime()
activate GameTimeManager
GameTimeManager --> Bonding: game_time
deactivate GameTimeManager
Bonding -> Bonding: calc delta
Bonding -> BondingFactory: create(bonding_level, bonding_gauge)
activate BondingFactory
BondingFactory --> Bonding: new_bonding = new ConcreteBonding()
Bonding -> Bonding: new_bonding.update(last_update_time)
deactivate BondingFactory
Bonding --> AI: new Bonding()
deactivate Bonding

alt Bonding Level Up
  AI -> ActionRepository: getCatActionsByBondingLevel(new_level)
  activate ActionRepository
  ActionRepository --> AI: new ConcreteCatAction
  deactivate ActionRepository
end alt
deactivate Bonding
AI -> Emotion: update(action_result.emotion_change)
activate Emotion
Emotion --> AI: new Emotion()
deactivate Emotion
AI -> Cat: result(ActionResult)
Cat -> Position: move(action_result.movement)
activate Position
Position --> Cat: new Position()
deactivate Position
Cat --> Client: void
deactivate Cat

@enduml